name: Continuous Integration
on: [pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: yarn lint
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
