name: Continuous Integration
on: [pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Linting
        uses: wearerequired/lint-action@v1.9.0
        with:
          eslint: true
          prettier: true
      - name: Build
        run: yarn build
